const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const { Op } = require('sequelize');

// Color constants for professional styling
const COLORS = {
  primary: '#1976d2',
  secondary: '#424242',
  success: '#2e7d32',
  warning: '#ed6c02',
  error: '#d32f2f',
  header: '#1a237e',
  lightGray: '#f5f5f5',
  border: '#e0e0e0',
  text: '#212121'
};

/**
 * Generate PDF report with professional styling
 */
exports.generatePDFReport = async (reportType, data, filters = {}) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50,
        size: 'A4',
        info: {
          Title: getReportTitle(reportType),
          Author: 'School Management System',
          Subject: getReportTitle(reportType),
          Creator: 'School Management System'
        }
      });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => {
        try {
          resolve(Buffer.concat(chunks));
        } catch (error) {
          reject(new Error(`Failed to create PDF buffer: ${error.message}`));
        }
      });
      doc.on('error', (error) => {
        reject(new Error(`PDF generation error: ${error.message}`));
      });

      // Professional Header with colored background
      const headerHeight = 80;
      doc.rect(0, 0, doc.page.width, headerHeight)
        .fillColor(COLORS.header)
        .fill();
      
      doc.fillColor('#ffffff')
        .fontSize(24)
        .font('Helvetica-Bold')
        .text('School Management System', 50, 20, { align: 'center', width: doc.page.width - 100 });
      
      doc.fontSize(18)
        .font('Helvetica')
        .text(getReportTitle(reportType), 50, 50, { align: 'center', width: doc.page.width - 100 });
      
      doc.fillColor(COLORS.text);
      let yPos = headerHeight + 30;

      // Report Info Box
      doc.rect(50, yPos, doc.page.width - 100, 60)
        .fillColor(COLORS.lightGray)
        .fill()
        .strokeColor(COLORS.border)
        .lineWidth(1)
        .stroke();
      
      doc.fillColor(COLORS.text)
        .fontSize(10)
        .font('Helvetica')
        .text(`Generated: ${new Date().toLocaleString('en-US', { 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric', 
          hour: '2-digit', 
          minute: '2-digit' 
        })}`, 60, yPos + 10);
      
      if (filters.startDate || filters.endDate) {
        doc.text(`Period: ${filters.startDate || 'N/A'} to ${filters.endDate || 'N/A'}`, 60, yPos + 25);
      }
      
      doc.text(`Report Type: ${getReportTitle(reportType)}`, 60, yPos + 40);
      
      yPos += 80;

      // Report Content
      switch (reportType) {
        case 'student-performance':
          yPos = generateStudentPerformancePDF(doc, data, yPos);
          break;
        case 'staff-performance':
          yPos = generateStaffPerformancePDF(doc, data, yPos);
          break;
        case 'finance':
          yPos = generateFinancePDF(doc, data, yPos);
          break;
        case 'attendance':
          yPos = generateAttendancePDF(doc, data, yPos);
          break;
        default:
          doc.fontSize(12).text('Report data not available', 50, yPos);
      }

      // Footer on each page - track page numbers manually
      let pageNumber = 0;
      const addFooter = () => {
        pageNumber++;
        const pageHeight = doc.page.height;
        const pageWidth = doc.page.width;
        doc.fontSize(8)
          .fillColor('#666666')
          .text(
            `Page ${pageNumber} | Generated by School Management System`,
            pageWidth / 2,
            pageHeight - 30,
            { align: 'center', width: pageWidth - 100 }
          );
      };

      // Add footer to each page
      doc.on('page', addFooter);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generate Excel report with professional styling
 */
exports.generateExcelReport = async (reportType, data, filters = {}) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'School Management System';
  workbook.created = new Date();
  workbook.modified = new Date();
  
  const worksheet = workbook.addWorksheet(getReportTitle(reportType), {
    pageSetup: {
      paperSize: 9, // A4
      orientation: 'portrait',
      margins: {
        left: 0.7,
        right: 0.7,
        top: 0.75,
        bottom: 0.75,
        header: 0.3,
        footer: 0.3
      }
    }
  });

  // Header styling
  const headerStyle = {
    font: { size: 18, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1a237e' } },
    alignment: { horizontal: 'center', vertical: 'middle' },
    border: {
      top: { style: 'thin', color: { argb: 'FF000000' } },
      bottom: { style: 'thin', color: { argb: 'FF000000' } },
      left: { style: 'thin', color: { argb: 'FF000000' } },
      right: { style: 'thin', color: { argb: 'FF000000' } }
    }
  };

  const subHeaderStyle = {
    font: { size: 14, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1976d2' } },
    alignment: { horizontal: 'center', vertical: 'middle' },
    border: {
      top: { style: 'thin', color: { argb: 'FF000000' } },
      bottom: { style: 'thin', color: { argb: 'FF000000' } },
      left: { style: 'thin', color: { argb: 'FF000000' } },
      right: { style: 'thin', color: { argb: 'FF000000' } }
    }
  };

  // Main header
  worksheet.mergeCells('A1:F1');
  worksheet.getCell('A1').value = 'School Management System';
  worksheet.getCell('A1').style = headerStyle;
  worksheet.getRow(1).height = 30;

  // Report title
  worksheet.mergeCells('A2:F2');
  worksheet.getCell('A2').value = getReportTitle(reportType);
  worksheet.getCell('A2').style = subHeaderStyle;
  worksheet.getRow(2).height = 25;

  // Report info
  worksheet.getCell('A3').value = `Generated: ${new Date().toLocaleString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric', 
    hour: '2-digit', 
    minute: '2-digit' 
  })}`;
  worksheet.getCell('A3').font = { size: 10, italic: true };
  
  if (filters.startDate || filters.endDate) {
    worksheet.getCell('A4').value = `Period: ${filters.startDate || 'N/A'} to ${filters.endDate || 'N/A'}`;
    worksheet.getCell('A4').font = { size: 10, italic: true };
  }

  let startRow = 6;

  switch (reportType) {
    case 'student-performance':
      startRow = generateStudentPerformanceExcel(worksheet, data, startRow);
      break;
    case 'staff-performance':
      startRow = generateStaffPerformanceExcel(worksheet, data, startRow);
      break;
    case 'finance':
      startRow = generateFinanceExcel(worksheet, data, startRow);
      break;
    case 'attendance':
      startRow = generateAttendanceExcel(worksheet, data, startRow);
      break;
  }

  // Auto-size columns
  worksheet.columns.forEach((column, index) => {
    let maxLength = 10;
    column.eachCell({ includeEmpty: false }, (cell) => {
      const cellValue = cell.value ? cell.value.toString() : '';
      maxLength = Math.max(maxLength, cellValue.length);
    });
    column.width = Math.min(Math.max(maxLength + 2, 12), 50);
  });

  // Footer
  worksheet.getRow(startRow + 2).getCell(1).value = `Generated by School Management System`;
  worksheet.getRow(startRow + 2).getCell(1).font = { size: 9, italic: true, color: { argb: 'FF666666' } };

  return workbook;
};

// Helper functions
function getReportTitle(reportType) {
  const titles = {
    'student-performance': 'Student Performance Report',
    'staff-performance': 'Staff Performance Report',
    'finance': 'Finance Report',
    'attendance': 'Attendance Report'
  };
  return titles[reportType] || 'Report';
}

// PDF Helper Functions
function drawTable(doc, data, headers, startY, columnWidths) {
  if (!data || !Array.isArray(data) || data.length === 0) {
    return startY;
  }
  
  const rowHeight = 25;
  const headerHeight = 30;
  const tableWidth = doc.page.width - 100;
  const startX = 50;
  
  let currentY = startY;
  
  // Draw header
  doc.rect(startX, currentY, tableWidth, headerHeight)
    .fillColor(COLORS.header)
    .fill()
    .strokeColor(COLORS.border)
    .lineWidth(1)
    .stroke();
  
  doc.fillColor('#ffffff')
    .fontSize(11)
    .font('Helvetica-Bold');
  
  let xPos = startX + 5;
  headers.forEach((header, index) => {
    doc.text(header, xPos, currentY + 8, { width: columnWidths[index] - 10, align: 'left' });
    xPos += columnWidths[index];
  });
  
  currentY += headerHeight;
  doc.fillColor(COLORS.text);
  
  // Draw rows
  data.forEach((row, rowIndex) => {
    if (currentY + rowHeight > doc.page.height - 50) {
      doc.addPage();
      currentY = 50;
      // Redraw header on new page
      doc.rect(startX, currentY, tableWidth, headerHeight)
        .fillColor(COLORS.header)
        .fill()
        .strokeColor(COLORS.border)
        .lineWidth(1)
        .stroke();
      doc.fillColor('#ffffff')
        .fontSize(11)
        .font('Helvetica-Bold');
      xPos = startX + 5;
      headers.forEach((header, index) => {
        doc.text(header, xPos, currentY + 8, { width: columnWidths[index] - 10, align: 'left' });
        xPos += columnWidths[index];
      });
      currentY += headerHeight;
      doc.fillColor(COLORS.text);
    }
    
    const fillColor = rowIndex % 2 === 0 ? COLORS.lightGray : '#ffffff';
    doc.rect(startX, currentY, tableWidth, rowHeight)
      .fillColor(fillColor)
      .fill()
      .strokeColor(COLORS.border)
      .lineWidth(0.5)
      .stroke();
    
    doc.fontSize(10)
      .font('Helvetica');
    
    xPos = startX + 5;
    row.forEach((cell, cellIndex) => {
      const cellValue = cell !== null && cell !== undefined ? cell.toString() : '';
      doc.text(cellValue, xPos, currentY + 7, { width: columnWidths[cellIndex] - 10, align: 'left' });
      xPos += columnWidths[cellIndex];
    });
    
    currentY += rowHeight;
  });
  
  return currentY + 20;
}

function drawSummaryBox(doc, title, items, startY) {
  if (!items || !Array.isArray(items) || items.length === 0) {
    return startY;
  }
  
  const boxHeight = 20 + (items.length * 20);
  const boxWidth = doc.page.width - 100;
  const startX = 50;
  
  if (startY + boxHeight > doc.page.height - 50) {
    doc.addPage();
    startY = 50;
  }
  
  // Title background
  doc.rect(startX, startY, boxWidth, 25)
    .fillColor(COLORS.primary)
    .fill()
    .strokeColor(COLORS.border)
    .lineWidth(1)
    .stroke();
  
  doc.fillColor('#ffffff')
    .fontSize(14)
    .font('Helvetica-Bold')
    .text(title, startX + 10, startY + 7);
  
  // Content background
  doc.rect(startX, startY + 25, boxWidth, boxHeight - 25)
    .fillColor(COLORS.lightGray)
    .fill()
    .strokeColor(COLORS.border)
    .lineWidth(1)
    .stroke();
  
  doc.fillColor(COLORS.text)
    .fontSize(11)
    .font('Helvetica');
  
  let yPos = startY + 35;
  items.forEach(item => {
    doc.text(item, startX + 10, yPos);
    yPos += 20;
  });
  
  return startY + boxHeight + 20;
}

function generateStudentPerformancePDF(doc, data, startY) {
  if (!data || (!data.summary && (!data.bySubject || data.bySubject.length === 0) && (!data.byClass || data.byClass.length === 0))) {
    doc.fontSize(12).text('No data available for the selected filters.', 50, startY);
    return startY + 30;
  }

  let yPos = startY;

  // Summary Section
  const summaryItems = [];
  if (data.summary) {
    summaryItems.push(`Total Grades: ${data.summary.totalGrades || 0}`);
    summaryItems.push(`Average Marks: ${(data.summary.averageMarks || 0).toFixed(2)}`);
    
    if (data.summary.gradeDistribution) {
      summaryItems.push('');
      summaryItems.push('Grade Distribution:');
      Object.entries(data.summary.gradeDistribution).forEach(([grade, count]) => {
        summaryItems.push(`  ${grade}: ${count}`);
      });
    }
  }
  
  if (summaryItems.length > 0) {
    yPos = drawSummaryBox(doc, 'Summary', summaryItems, yPos);
  }

  // Performance by Subject Table
  if (data.bySubject && data.bySubject.length > 0) {
    const headers = ['Subject', 'Average Marks'];
    const tableData = data.bySubject.map(subject => [
      subject.subject_name || subject.name || subject.subject || 'Unknown',
      (subject.average_marks || subject.average || 0).toFixed(2)
    ]);
    const columnWidths = [(doc.page.width - 100) * 0.7, (doc.page.width - 100) * 0.3];
    yPos = drawTable(doc, tableData, headers, yPos, columnWidths);
  }

  // Performance by Class Table
  if (data.byClass && data.byClass.length > 0) {
    const headers = ['Class', 'Average Marks'];
    const tableData = data.byClass.map(cls => [
      cls.class_name || cls.name || cls.class || 'Unknown',
      (cls.average_marks || cls.average || 0).toFixed(2)
    ]);
    const columnWidths = [(doc.page.width - 100) * 0.7, (doc.page.width - 100) * 0.3];
    yPos = drawTable(doc, tableData, headers, yPos, columnWidths);
  }

  return yPos;
}

function generateStaffPerformancePDF(doc, data, startY) {
  let yPos = startY;

  // Summary Section
  const summaryItems = [];
  if (data.summary) {
    summaryItems.push(`Total Teachers: ${data.summary.totalTeachers || 0}`);
    summaryItems.push(`Active Teachers: ${data.summary.activeTeachers || 0}`);
    summaryItems.push(`Total Attendance Marked: ${data.summary.totalAttendanceMarked || 0}`);
    summaryItems.push(`Total Exams: ${data.summary.totalExams || 0}`);
  }
  
  if (summaryItems.length > 0) {
    yPos = drawSummaryBox(doc, 'Summary', summaryItems, yPos);
  }

  // Teacher Details Table
  if (data.teachers && data.teachers.length > 0) {
    const headers = ['Name', 'Email', 'Classes', 'Attendance', 'Exams', 'Grades'];
    const tableData = data.teachers.map(teacher => [
      teacher.name || 'N/A',
      teacher.email || 'N/A',
      (teacher.totalClasses || teacher.classes || 0).toString(),
      (teacher.attendanceMarked || 0).toString(),
      (teacher.examsCreated || 0).toString(),
      (teacher.gradesEntered || 0).toString()
    ]);
    const columnWidths = [
      (doc.page.width - 100) * 0.25,
      (doc.page.width - 100) * 0.25,
      (doc.page.width - 100) * 0.12,
      (doc.page.width - 100) * 0.12,
      (doc.page.width - 100) * 0.13,
      (doc.page.width - 100) * 0.13
    ];
    yPos = drawTable(doc, tableData, headers, yPos, columnWidths);
  }

  return yPos;
}

function generateFinancePDF(doc, data, startY) {
  let yPos = startY;

  // Summary Section
  const summaryItems = [];
  if (data.summary) {
    summaryItems.push(`Total Fees: $${(data.summary.totalFees || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
    summaryItems.push(`Total Payments: $${(data.summary.totalPayments || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
    summaryItems.push(`Pending Amount: $${(data.summary.pendingAmount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
    if (data.summary.collectionRate !== undefined) {
      summaryItems.push(`Collection Rate: ${(data.summary.collectionRate || 0).toFixed(2)}%`);
    }
  }
  
  if (summaryItems.length > 0) {
    yPos = drawSummaryBox(doc, 'Summary', summaryItems, yPos);
  }

  // Fee Type Breakdown Table
  if (data.feeTypeBreakdown && data.feeTypeBreakdown.length > 0) {
    const headers = ['Fee Type', 'Amount'];
    const tableData = data.feeTypeBreakdown.map(item => [
      item.fee_type || item.type || item.name || 'Unknown',
      `$${(item.amount || item.total || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ]);
    const columnWidths = [(doc.page.width - 100) * 0.6, (doc.page.width - 100) * 0.4];
    yPos = drawTable(doc, tableData, headers, yPos, columnWidths);
  }

  // Monthly Payments Table
  if (data.monthlyPayments && data.monthlyPayments.length > 0) {
    const headers = ['Month', 'Amount'];
    const tableData = data.monthlyPayments.map(item => [
      item.month || item.name || 'Unknown',
      `$${(item.amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ]);
    const columnWidths = [(doc.page.width - 100) * 0.6, (doc.page.width - 100) * 0.4];
    yPos = drawTable(doc, tableData, headers, yPos, columnWidths);
  }

  return yPos;
}

function generateAttendancePDF(doc, data, startY) {
  let yPos = startY;

  // Summary Section
  const summaryItems = [];
  if (data.summary) {
    summaryItems.push(`Total Records: ${data.summary.totalRecords || data.summary.total || 0}`);
    summaryItems.push(`Present: ${data.summary.present || 0}`);
    summaryItems.push(`Absent: ${data.summary.absent || 0}`);
    if (data.summary.late !== undefined) {
      summaryItems.push(`Late: ${data.summary.late || 0}`);
    }
    const attendanceRate = data.summary.attendanceRate !== undefined 
      ? (data.summary.attendanceRate * 100).toFixed(2)
      : (data.summary.attendanceRate || 0).toFixed(2);
    summaryItems.push(`Attendance Rate: ${attendanceRate}%`);
  }
  
  if (summaryItems.length > 0) {
    yPos = drawSummaryBox(doc, 'Summary', summaryItems, yPos);
  }

  // Daily Trend Table
  if (data.dailyTrend && data.dailyTrend.length > 0) {
    const headers = ['Date', 'Attendance Rate'];
    const tableData = data.dailyTrend.map(item => {
      const rate = item.attendanceRate !== undefined 
        ? (item.attendanceRate * 100).toFixed(2) + '%'
        : (item.rate || 0).toFixed(2) + '%';
      return [
        item.date || item.name || 'Unknown',
        rate
      ];
    });
    const columnWidths = [(doc.page.width - 100) * 0.6, (doc.page.width - 100) * 0.4];
    yPos = drawTable(doc, tableData, headers, yPos, columnWidths);
  }

  return yPos;
}

// Excel Helper Functions
function applyTableStyle(worksheet, startRow, endRow, startCol, endCol, hasHeader = true) {
  const headerStyle = {
    font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1976d2' } },
    alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
    border: {
      top: { style: 'thin', color: { argb: 'FF000000' } },
      bottom: { style: 'thin', color: { argb: 'FF000000' } },
      left: { style: 'thin', color: { argb: 'FF000000' } },
      right: { style: 'thin', color: { argb: 'FF000000' } }
    }
  };

  const cellStyle = {
    font: { size: 10 },
    alignment: { vertical: 'middle', wrapText: true },
    border: {
      top: { style: 'thin', color: { argb: 'FFE0E0E0' } },
      bottom: { style: 'thin', color: { argb: 'FFE0E0E0' } },
      left: { style: 'thin', color: { argb: 'FFE0E0E0' } },
      right: { style: 'thin', color: { argb: 'FFE0E0E0' } }
    }
  };

  for (let row = startRow; row <= endRow; row++) {
    const isHeaderRow = hasHeader && row === startRow;
    for (let col = startCol; col <= endCol; col++) {
      const cell = worksheet.getCell(row, col);
      if (isHeaderRow) {
        cell.style = headerStyle;
      } else {
        cell.style = {
          ...cellStyle,
          fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: row % 2 === 0 ? 'FFF5F5F5' : 'FFFFFFFF' } }
        };
      }
    }
    worksheet.getRow(row).height = isHeaderRow ? 25 : 20;
  }
}

function generateStudentPerformanceExcel(worksheet, data, startRow) {
  let row = startRow;
  
  if (!data || (!data.summary && (!data.bySubject || data.bySubject.length === 0) && (!data.byClass || data.byClass.length === 0))) {
    worksheet.getCell(`A${row}`).value = 'No data available for the selected filters.';
    worksheet.getCell(`A${row}`).font = { italic: true, color: { argb: 'FF666666' } };
    return row + 2;
  }
  
  // Summary section
  worksheet.mergeCells(`A${row}:B${row}`);
  worksheet.getCell(`A${row}`).value = 'Summary';
  worksheet.getCell(`A${row}`).style = {
    font: { size: 12, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1976d2' } },
    alignment: { horizontal: 'center', vertical: 'middle' }
  };
  worksheet.getRow(row).height = 25;
  row++;

  if (data.summary) {
    worksheet.getCell(`A${row}`).value = 'Total Grades';
    worksheet.getCell(`B${row}`).value = data.summary.totalGrades || 0;
    row++;
    worksheet.getCell(`A${row}`).value = 'Average Marks';
    worksheet.getCell(`B${row}`).value = data.summary.averageMarks || 0;
    worksheet.getCell(`B${row}`).numFmt = '0.00';
    row++;
    row++;
  }

  // Grade Distribution
  if (data.summary?.gradeDistribution) {
    const gradeStartRow = row;
    worksheet.mergeCells(`A${row}:B${row}`);
    worksheet.getCell(`A${row}`).value = 'Grade Distribution';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Grade';
    worksheet.getCell(`B${row}`).value = 'Count';
    row++;
    const gradeEntries = Object.entries(data.summary.gradeDistribution);
    gradeEntries.forEach(([grade, count]) => {
      worksheet.getCell(`A${row}`).value = grade;
      worksheet.getCell(`B${row}`).value = count;
      row++;
    });
    applyTableStyle(worksheet, gradeStartRow + 1, row - 1, 1, 2);
    row++;
  }

  // By Subject
  if (data.bySubject && data.bySubject.length > 0) {
    const subjectStartRow = row;
    worksheet.mergeCells(`A${row}:B${row}`);
    worksheet.getCell(`A${row}`).value = 'Performance by Subject';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Subject';
    worksheet.getCell(`B${row}`).value = 'Average Marks';
    row++;
    data.bySubject.forEach(subject => {
      worksheet.getCell(`A${row}`).value = subject.subject_name || subject.name || subject.subject || 'Unknown';
      worksheet.getCell(`B${row}`).value = subject.average_marks || subject.average || 0;
      worksheet.getCell(`B${row}`).numFmt = '0.00';
      row++;
    });
    applyTableStyle(worksheet, subjectStartRow + 1, row - 1, 1, 2);
    row++;
  }

  // By Class
  if (data.byClass && data.byClass.length > 0) {
    const classStartRow = row;
    worksheet.mergeCells(`A${row}:B${row}`);
    worksheet.getCell(`A${row}`).value = 'Performance by Class';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Class';
    worksheet.getCell(`B${row}`).value = 'Average Marks';
    row++;
    data.byClass.forEach(cls => {
      worksheet.getCell(`A${row}`).value = cls.class_name || cls.name || cls.class || 'Unknown';
      worksheet.getCell(`B${row}`).value = cls.average_marks || cls.average || 0;
      worksheet.getCell(`B${row}`).numFmt = '0.00';
      row++;
    });
    applyTableStyle(worksheet, classStartRow + 1, row - 1, 1, 2);
  }

  return row;
}

function generateStaffPerformanceExcel(worksheet, data, startRow) {
  let row = startRow;
  
  // Summary
  worksheet.mergeCells(`A${row}:F${row}`);
  worksheet.getCell(`A${row}`).value = 'Summary';
  worksheet.getCell(`A${row}`).style = {
    font: { size: 12, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1976d2' } },
    alignment: { horizontal: 'center', vertical: 'middle' }
  };
  worksheet.getRow(row).height = 25;
  row++;

  if (data.summary) {
    worksheet.getCell(`A${row}`).value = 'Total Teachers';
    worksheet.getCell(`B${row}`).value = data.summary.totalTeachers || 0;
    row++;
    worksheet.getCell(`A${row}`).value = 'Active Teachers';
    worksheet.getCell(`B${row}`).value = data.summary.activeTeachers || 0;
    row++;
    worksheet.getCell(`A${row}`).value = 'Total Attendance Marked';
    worksheet.getCell(`B${row}`).value = data.summary.totalAttendanceMarked || 0;
    row++;
    worksheet.getCell(`A${row}`).value = 'Total Exams';
    worksheet.getCell(`B${row}`).value = data.summary.totalExams || 0;
    row++;
    row++;
  }

  // Teacher Details
  if (data.teachers && data.teachers.length > 0) {
    const teacherStartRow = row;
    worksheet.mergeCells(`A${row}:F${row}`);
    worksheet.getCell(`A${row}`).value = 'Teacher Details';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Name';
    worksheet.getCell(`B${row}`).value = 'Email';
    worksheet.getCell(`C${row}`).value = 'Classes';
    worksheet.getCell(`D${row}`).value = 'Attendance Marked';
    worksheet.getCell(`E${row}`).value = 'Exams Created';
    worksheet.getCell(`F${row}`).value = 'Grades Entered';
    row++;
    data.teachers.forEach(teacher => {
      worksheet.getCell(`A${row}`).value = teacher.name || 'N/A';
      worksheet.getCell(`B${row}`).value = teacher.email || 'N/A';
      worksheet.getCell(`C${row}`).value = teacher.totalClasses || teacher.classes || 0;
      worksheet.getCell(`D${row}`).value = teacher.attendanceMarked || 0;
      worksheet.getCell(`E${row}`).value = teacher.examsCreated || 0;
      worksheet.getCell(`F${row}`).value = teacher.gradesEntered || 0;
      row++;
    });
    applyTableStyle(worksheet, teacherStartRow + 1, row - 1, 1, 6);
  }

  return row;
}

function generateFinanceExcel(worksheet, data, startRow) {
  let row = startRow;
  
  // Summary
  worksheet.mergeCells(`A${row}:B${row}`);
  worksheet.getCell(`A${row}`).value = 'Summary';
  worksheet.getCell(`A${row}`).style = {
    font: { size: 12, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1976d2' } },
    alignment: { horizontal: 'center', vertical: 'middle' }
  };
  worksheet.getRow(row).height = 25;
  row++;

  if (data.summary) {
    worksheet.getCell(`A${row}`).value = 'Total Fees';
    worksheet.getCell(`B${row}`).value = data.summary.totalFees || 0;
    worksheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    row++;
    worksheet.getCell(`A${row}`).value = 'Total Payments';
    worksheet.getCell(`B${row}`).value = data.summary.totalPayments || 0;
    worksheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    row++;
    worksheet.getCell(`A${row}`).value = 'Pending Amount';
    worksheet.getCell(`B${row}`).value = data.summary.pendingAmount || 0;
    worksheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    row++;
    if (data.summary.collectionRate !== undefined) {
      worksheet.getCell(`A${row}`).value = 'Collection Rate';
      worksheet.getCell(`B${row}`).value = (data.summary.collectionRate || 0) / 100;
      worksheet.getCell(`B${row}`).numFmt = '0.00%';
      row++;
    }
    row++;
  }

  // Fee Type Breakdown
  if (data.feeTypeBreakdown && data.feeTypeBreakdown.length > 0) {
    const feeStartRow = row;
    worksheet.mergeCells(`A${row}:B${row}`);
    worksheet.getCell(`A${row}`).value = 'Fee Type Breakdown';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Fee Type';
    worksheet.getCell(`B${row}`).value = 'Amount';
    row++;
    data.feeTypeBreakdown.forEach(item => {
      worksheet.getCell(`A${row}`).value = item.fee_type || item.type || item.name || 'Unknown';
      worksheet.getCell(`B${row}`).value = item.amount || item.total || 0;
      worksheet.getCell(`B${row}`).numFmt = '$#,##0.00';
      row++;
    });
    applyTableStyle(worksheet, feeStartRow + 1, row - 1, 1, 2);
    row++;
  }

  // Monthly Payments
  if (data.monthlyPayments && data.monthlyPayments.length > 0) {
    const monthlyStartRow = row;
    worksheet.mergeCells(`A${row}:B${row}`);
    worksheet.getCell(`A${row}`).value = 'Monthly Payments';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Month';
    worksheet.getCell(`B${row}`).value = 'Amount';
    row++;
    data.monthlyPayments.forEach(item => {
      worksheet.getCell(`A${row}`).value = item.month || item.name || 'Unknown';
      worksheet.getCell(`B${row}`).value = item.amount || 0;
      worksheet.getCell(`B${row}`).numFmt = '$#,##0.00';
      row++;
    });
    applyTableStyle(worksheet, monthlyStartRow + 1, row - 1, 1, 2);
  }

  return row;
}

function generateAttendanceExcel(worksheet, data, startRow) {
  let row = startRow;
  
  // Summary
  worksheet.mergeCells(`A${row}:B${row}`);
  worksheet.getCell(`A${row}`).value = 'Summary';
  worksheet.getCell(`A${row}`).style = {
    font: { size: 12, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1976d2' } },
    alignment: { horizontal: 'center', vertical: 'middle' }
  };
  worksheet.getRow(row).height = 25;
  row++;

  if (data.summary) {
    worksheet.getCell(`A${row}`).value = 'Total Records';
    worksheet.getCell(`B${row}`).value = data.summary.totalRecords || data.summary.total || 0;
    row++;
    worksheet.getCell(`A${row}`).value = 'Present';
    worksheet.getCell(`B${row}`).value = data.summary.present || 0;
    row++;
    worksheet.getCell(`A${row}`).value = 'Absent';
    worksheet.getCell(`B${row}`).value = data.summary.absent || 0;
    row++;
    if (data.summary.late !== undefined) {
      worksheet.getCell(`A${row}`).value = 'Late';
      worksheet.getCell(`B${row}`).value = data.summary.late || 0;
      row++;
    }
    worksheet.getCell(`A${row}`).value = 'Attendance Rate';
    const attendanceRate = data.summary.attendanceRate !== undefined 
      ? data.summary.attendanceRate 
      : (data.summary.attendanceRate || 0) / 100;
    worksheet.getCell(`B${row}`).value = attendanceRate;
    worksheet.getCell(`B${row}`).numFmt = '0.00%';
    row++;
    row++;
  }

  // Daily Trend
  if (data.dailyTrend && data.dailyTrend.length > 0) {
    const trendStartRow = row;
    worksheet.mergeCells(`A${row}:B${row}`);
    worksheet.getCell(`A${row}`).value = 'Daily Trend';
    worksheet.getCell(`A${row}`).style = {
      font: { size: 11, bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF424242' } },
      alignment: { horizontal: 'center', vertical: 'middle' }
    };
    row++;
    worksheet.getCell(`A${row}`).value = 'Date';
    worksheet.getCell(`B${row}`).value = 'Attendance Rate';
    row++;
    data.dailyTrend.forEach(item => {
      worksheet.getCell(`A${row}`).value = item.date || item.name || 'Unknown';
      const rate = item.attendanceRate !== undefined 
        ? item.attendanceRate 
        : (item.rate || 0) / 100;
      worksheet.getCell(`B${row}`).value = rate;
      worksheet.getCell(`B${row}`).numFmt = '0.00%';
      row++;
    });
    applyTableStyle(worksheet, trendStartRow + 1, row - 1, 1, 2);
  }

  return row;
}

/**
 * Generate Report Card PDF for a specific student
 */
exports.generateReportCardPDF = async (student, grades, academicYear = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50,
        size: 'A4',
        info: {
          Title: `Report Card - ${student.first_name} ${student.last_name}`,
          Author: 'School Management System',
          Subject: 'Student Report Card',
          Creator: 'School Management System'
        }
      });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => {
        try {
          resolve(Buffer.concat(chunks));
        } catch (error) {
          reject(new Error(`Failed to create PDF buffer: ${error.message}`));
        }
      });
      doc.on('error', (error) => {
        reject(new Error(`PDF generation error: ${error.message}`));
      });

      // Header
      const headerHeight = 100;
      doc.rect(0, 0, doc.page.width, headerHeight)
        .fillColor(COLORS.header)
        .fill();
      
      doc.fillColor('#ffffff')
        .fontSize(24)
        .font('Helvetica-Bold')
        .text('SCHOOL MANAGEMENT SYSTEM', 50, 20, { align: 'center', width: doc.page.width - 100 });
      
      doc.fontSize(18)
        .font('Helvetica')
        .text('STUDENT REPORT CARD', 50, 50, { align: 'center', width: doc.page.width - 100 });

      if (academicYear) {
        doc.fontSize(12)
          .text(`Academic Year: ${academicYear}`, 50, 75, { align: 'center', width: doc.page.width - 100 });
      }

      let yPos = headerHeight + 30;

      // Student Information Box
      doc.rect(50, yPos, doc.page.width - 100, 100)
        .fillColor(COLORS.lightGray)
        .fill()
        .strokeColor(COLORS.border)
        .lineWidth(1)
        .stroke();
      
      doc.fillColor(COLORS.text)
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Student Information', 60, yPos + 10);
      
      doc.fontSize(10)
        .font('Helvetica')
        .text(`Name: ${student.first_name} ${student.last_name}`, 60, yPos + 30)
        .text(`Student ID: ${student.student_id || 'N/A'}`, 60, yPos + 45)
        .text(`Class: ${student.class?.name || 'N/A'}`, 60, yPos + 60)
        .text(`Date of Birth: ${student.date_of_birth ? new Date(student.date_of_birth).toLocaleDateString() : 'N/A'}`, 60, yPos + 75);

      yPos += 120;

      // Grades Table
      if (grades && grades.length > 0) {
        // Group grades by exam
        const gradesByExam = {};
        grades.forEach(grade => {
          const examName = grade.exam?.name || 'Unknown Exam';
          if (!gradesByExam[examName]) {
            gradesByExam[examName] = [];
          }
          gradesByExam[examName].push(grade);
        });

        Object.keys(gradesByExam).forEach(examName => {
          const examGrades = gradesByExam[examName];
          
          // Exam Header
          doc.fillColor(COLORS.header)
            .fontSize(12)
            .font('Helvetica-Bold')
            .text(examName, 50, yPos);
          
          yPos += 20;

          // Table Headers
          const tableTop = yPos;
          const tableLeft = 50;
          const tableWidth = doc.page.width - 100;
          const colWidths = [tableWidth * 0.4, tableWidth * 0.2, tableWidth * 0.2, tableWidth * 0.2];
          
          doc.fillColor(COLORS.header)
            .rect(tableLeft, tableTop, tableWidth, 25)
            .fill();
          
          doc.fillColor('#ffffff')
            .fontSize(10)
            .font('Helvetica-Bold')
            .text('Subject', tableLeft + 5, tableTop + 8)
            .text('Marks', tableLeft + colWidths[0] + 5, tableTop + 8)
            .text('Total', tableLeft + colWidths[0] + colWidths[1] + 5, tableTop + 8)
            .text('Grade', tableLeft + colWidths[0] + colWidths[1] + colWidths[2] + 5, tableTop + 8);

          yPos += 25;

          // Table Rows
          let totalMarks = 0;
          let totalObtained = 0;
          
          examGrades.forEach((grade, index) => {
            const rowY = yPos + (index * 20);
            const marksObtained = grade.marks_obtained || 0;
            const totalMarksForSubject = grade.exam?.total_marks || 100;
            
            totalMarks += totalMarksForSubject;
            totalObtained += marksObtained;

            doc.fillColor(index % 2 === 0 ? '#ffffff' : COLORS.lightGray)
              .rect(tableLeft, rowY, tableWidth, 20)
              .fill();
            
            doc.fillColor(COLORS.text)
              .fontSize(9)
              .font('Helvetica')
              .text(grade.subject?.name || 'Unknown', tableLeft + 5, rowY + 6)
              .text(marksObtained.toString(), tableLeft + colWidths[0] + 5, rowY + 6)
              .text(totalMarksForSubject.toString(), tableLeft + colWidths[0] + colWidths[1] + 5, rowY + 6)
              .text(grade.grade || 'N/A', tableLeft + colWidths[0] + colWidths[1] + colWidths[2] + 5, rowY + 6);
          });

          yPos += (examGrades.length * 20) + 10;

          // Total Row
          const percentage = totalMarks > 0 ? ((totalObtained / totalMarks) * 100).toFixed(2) : 0;
          doc.fillColor(COLORS.success)
            .rect(tableLeft, yPos, tableWidth, 25)
            .fill();
          
          doc.fillColor('#ffffff')
            .fontSize(10)
            .font('Helvetica-Bold')
            .text('TOTAL', tableLeft + 5, yPos + 8)
            .text(totalObtained.toString(), tableLeft + colWidths[0] + 5, yPos + 8)
            .text(totalMarks.toString(), tableLeft + colWidths[0] + colWidths[1] + 5, yPos + 8)
            .text(`${percentage}%`, tableLeft + colWidths[0] + colWidths[1] + colWidths[2] + 5, yPos + 8);

          yPos += 35;

          // Check if we need a new page
          if (yPos > doc.page.height - 100) {
            doc.addPage();
            yPos = 50;
          }
        });
      } else {
        doc.fillColor(COLORS.text)
          .fontSize(12)
          .text('No grades available for this student.', 50, yPos);
      }

      // Footer
      let pageNumber = 0;
      const addFooter = () => {
        pageNumber++;
        const pageHeight = doc.page.height;
        const pageWidth = doc.page.width;
        doc.fontSize(8)
          .fillColor('#666666')
          .text(
            `Page ${pageNumber} | Generated: ${new Date().toLocaleString()}`,
            pageWidth / 2,
            pageHeight - 30,
            { align: 'center', width: pageWidth - 100 }
          );
      };

      doc.on('page', addFooter);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generate Payment Receipt PDF
 */
exports.generatePaymentReceiptPDF = async (payment, fee, student) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50,
        size: 'A4',
        info: {
          Title: `Payment Receipt - ${payment.receipt_number}`,
          Author: 'School Management System',
          Subject: 'Payment Receipt',
          Creator: 'School Management System'
        }
      });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => {
        try {
          resolve(Buffer.concat(chunks));
        } catch (error) {
          reject(new Error(`Failed to create PDF buffer: ${error.message}`));
        }
      });
      doc.on('error', (error) => {
        reject(new Error(`PDF generation error: ${error.message}`));
      });

      // Header
      const headerHeight = 80;
      doc.rect(0, 0, doc.page.width, headerHeight)
        .fillColor(COLORS.header)
        .fill();
      
      doc.fillColor('#ffffff')
        .fontSize(24)
        .font('Helvetica-Bold')
        .text('SCHOOL MANAGEMENT SYSTEM', 50, 20, { align: 'center', width: doc.page.width - 100 });
      
      doc.fontSize(18)
        .font('Helvetica')
        .text('PAYMENT RECEIPT', 50, 50, { align: 'center', width: doc.page.width - 100 });

      let yPos = headerHeight + 40;

      // Receipt Number (Large)
      doc.fillColor(COLORS.text)
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(`Receipt No: ${payment.receipt_number || 'N/A'}`, 50, yPos, { align: 'right', width: doc.page.width - 100 });

      yPos += 30;

      // Receipt Details Box
      doc.rect(50, yPos, doc.page.width - 100, 200)
        .fillColor(COLORS.lightGray)
        .fill()
        .strokeColor(COLORS.border)
        .lineWidth(1)
        .stroke();
      
      doc.fillColor(COLORS.text)
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Payment Details', 60, yPos + 15);
      
      doc.fontSize(10)
        .font('Helvetica')
        .text(`Date: ${payment.payment_date ? new Date(payment.payment_date).toLocaleDateString() : 'N/A'}`, 60, yPos + 40)
        .text(`Payment Method: ${payment.payment_method ? payment.payment_method.replace('_', ' ').toUpperCase() : 'N/A'}`, 60, yPos + 55)
        .text(`Amount: $${parseFloat(payment.amount || 0).toFixed(2)}`, 60, yPos + 70);

      if (payment.transaction_id) {
        doc.text(`Transaction ID: ${payment.transaction_id}`, 60, yPos + 85);
      }

      yPos += 100;

      // Student Information
      doc.fontSize(12)
        .font('Helvetica-Bold')
        .text('Student Information', 60, yPos);
      
      doc.fontSize(10)
        .font('Helvetica')
        .text(`Name: ${student.first_name} ${student.last_name}`, 60, yPos + 20)
        .text(`Student ID: ${student.student_id || 'N/A'}`, 60, yPos + 35)
        .text(`Class: ${student.class?.name || 'N/A'}`, 60, yPos + 50);

      yPos += 80;

      // Fee Information
      if (fee) {
        doc.fontSize(12)
          .font('Helvetica-Bold')
          .text('Fee Information', 60, yPos);
        
        doc.fontSize(10)
          .font('Helvetica')
          .text(`Fee Type: ${fee.fee_type || 'N/A'}`, 60, yPos + 20)
          .text(`Total Amount: $${parseFloat(fee.amount || 0).toFixed(2)}`, 60, yPos + 35)
          .text(`Due Date: ${fee.due_date ? new Date(fee.due_date).toLocaleDateString() : 'N/A'}`, 60, yPos + 50);
      }

      yPos += 100;

      // Amount in Words (optional)
      const amountInWords = convertNumberToWords(parseFloat(payment.amount || 0));
      doc.fontSize(10)
        .font('Helvetica')
        .text(`Amount in Words: ${amountInWords}`, 60, yPos, { width: doc.page.width - 120 });

      yPos += 40;

      // Notes
      if (payment.notes) {
        doc.fontSize(10)
          .font('Helvetica')
          .text(`Notes: ${payment.notes}`, 60, yPos, { width: doc.page.width - 120 });
        yPos += 30;
      }

      // Footer with signature line
      yPos = doc.page.height - 120;
      doc.strokeColor(COLORS.border)
        .lineWidth(1)
        .moveTo(60, yPos)
        .lineTo(250, yPos)
        .stroke();
      
      doc.fontSize(9)
        .fillColor('#666666')
        .text('Authorized Signature', 60, yPos + 5);

      // Footer
      doc.fontSize(8)
        .fillColor('#666666')
        .text(
          `Generated: ${new Date().toLocaleString()} | School Management System`,
          doc.page.width / 2,
          doc.page.height - 30,
          { align: 'center', width: doc.page.width - 100 }
        );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

// Helper function to convert number to words (simple implementation)
function convertNumberToWords(num) {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten',
    'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  if (num === 0) return 'Zero';
  if (num < 20) return ones[Math.floor(num)];
  if (num < 100) {
    return tens[Math.floor(num / 10)] + (num % 10 !== 0 ? ' ' + ones[num % 10] : '');
  }
  if (num < 1000) {
    return ones[Math.floor(num / 100)] + ' Hundred' + (num % 100 !== 0 ? ' ' + convertNumberToWords(num % 100) : '');
  }
  if (num < 1000000) {
    return convertNumberToWords(Math.floor(num / 1000)) + ' Thousand' + (num % 1000 !== 0 ? ' ' + convertNumberToWords(num % 1000) : '');
  }
  return 'Large Amount';
}